App:
  AppVersion: 1.0.0
  Port: 8080
  Mode: Development
  Debug: false
logger:
  Level: info
  Encoding: json
  Development: true
  DisableCaller: false
  DisableStacktrace: false

mongo:
  Uri: mongodb://admin:secretpassword@127.0.0.1:27017/
