version: "3.8"

services:
  mongodb:
    image: mongo:8.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # WARNING: Cannot init db without mount a entrypoint file.
      # MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - mongo_network
    ports:
      - "${MONGODB_PORT}:27017"

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local

networks:
  mongo_network:
    driver: bridge
